name: Python checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "films/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder GH Action step
        run: echo "Hello Action!"
